query GetCalendarMonth($epochStart: Int!, $epochEnd: Int!, $tz: String!) {
  calendar(
    input: { endTime: $epochEnd, startTime: $epochStart, timeZone: $tz }
  ) {
    day
    events {
      id
      title
      comment
      dayEventStart
      endTime
      repeat {
        repeatData
        repeatUntil
        delay
        repeatType
      }
    }
  }
}
